In [5]:
#task1 
my_file = open("numbers.txt", "w")
numbers_list = [8, 65, 40, 72]
for numbers in numbers_list:
    my_file.write(str(numbers))
    my_file.write('\n')
my_file.close()

#reading
with open("numbers.txt", "r") as my_file:
    data = my_file.read().replace('\n', ',')
    print(data)
my_file.close()


#appending
my_file = open("numbers.txt", "a")
my_file.write("\n we have a short list)
my_file.close()







    
    


SyntaxError: EOL while scanning string literal (Temp/ipykernel_39880/300624381.py, line 18)

In [30]:
#task 2
percentage_mark = int(input("What is your percentage mark"))
if percentage_mark >= 80:
    print("A")

def function_grade(percentage_mark):
    print(percentage_mark)

A


In [47]:
#task 3
#1
import numpy as np
array = np.arange(0, 10)
print(array)

#2
bool_array = np.ones((3,4), dtype=bool)
print(bool_array)

#3
array = np.arange(1, 11)
print(array)
array[1::2]

#4
array = np.arange(1, 11)
print(array)
array[array%2==1] = -1
print(array)


#5
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
newArray = np.reshape(array, (2, 5))
print(newArray)


#6
a = np.arange(1, 10).reshape(3,3)
b= np.arange(11, 20).reshape(3,3)
print(a)
print(b)
c = np.dot(a, b)
print(c)
total_sum =np.sum(c)


[0 1 2 3 4 5 6 7 8 9]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[-1  2 -1  4 -1  6 -1  8 -1 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]
